### ISSUE TITLE
Fake selection container makes editable grow

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1106]
This happens in the documentation website:

![aug-25-2017 09-47-20](https://user-images.githubusercontent.com/156149/29704528-7fd77a96-897a-11e7-9664-c7b0e93454bf.gif)

**Comment by Reinmar** [comment]
I guess it needs to be styled to have height:0 and overflow: hidden. Its current styling doesn't reset its height so perhaps that's what expands the content.

**Comment by szymonkups** [comment]
It looks like docs page adds its custom styles to the last editable's child:
```
.ck-editor .ck-editor__editable > :first-child {
	margin-top: 0;
}

.ck-editor .ck-editor__editable > :last-child {
	margin-bottom: 0;
}
```
Question is - should we somehow be prepared for such styling or this should be on integrator's side, knowing that fake selection exists and is added at the end of editable sometimes?

**Comment by Reinmar** [comment]
Fake sel container's styles should be bulletproof. This is its first real-life integration and the styles blew up.

Since our reset CSS will not ensure proper specificity anyway, I'm for using inline styles there.

**Comment by szymonkups** [comment]
Above example is not a matter of fake selection container styles but selector on docs site. Styles remove margin from the last block of the editor's contents. When we append fake selection container there `margin:0` is applied to it. This does not change anything on the selection container, but now last visible block in the editor is not a `:last-child` so it gets normal margin. So it is a matter of changing the selector or moving fake selection container to other container, because adding it to the end of the editable will always mess with `:last-child` selector.

**Comment by Reinmar** [comment]
CSS, I hate you ;<! Let's change the selector ;|
