### ISSUE TITLE
[FF] Selection split by widgets should be merged in model to one range

### ISSUE THREAD

**Issue by ma2ciek** [ckeditor/ckeditor5-engine#1156]
FF split the selection into two ranges because of the `contenteditable=false` attribute in the widget. This causes two problems. First, the selection that contains multiple ranges is not supported well yet, and second, that we can't select an image element.

**Comment by Reinmar** [comment]
If we can do that, we would avoid many issues with handling unnecessarily multi-range selections.

Of course, if we'll fix the selection on model->view conversion, then it will be re-rendered and there's a question of what Firefox will do with it. Especially, if we'll re-render the selection while it's being made by dnd.

**Comment by scofalik** [comment]
This isn't that easy because in FF I cannot drag selection _after_ the image:

![image](https://user-images.githubusercontent.com/1502228/31117323-b2ad00e4-a829-11e7-8a74-9755e6d239ff.png)

When I drag on a "Quote" the selection is not made after the image. Funny, when I drag from "Quote" backwards above the image it works correctly (in DOM - although I expected three ranges and there are two, but they cover the selected area).

From what I've seen, there is an error thrown when I try to expand a selection between two nested editables (collapse in one, extend to other one). I tried to overcome this and use all ranges in selection to build a range that covers all of them but FF has problems with setting such selection. Look at this fiddle: https://jsfiddle.net/kx2aatd6/

Do you have any ideas how we could tackle this issue?

**Comment by scofalik** [comment]
I had a wrong fiddle previously, updated it: https://jsfiddle.net/kx2aatd6/2/.

**Comment by scofalik** [comment]
Hmm, it looks like not only Firefox has a problem with such selection... So does Chrome... Or I did something wrong?
