### ISSUE TITLE
Model utils (such as insertContent()) should not use model.change() internally

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1218]
I think that we agreed that this will be confusing why you can use them without wrapping them and that you need to use `model.change()` to do any other changes.

However, I don't remember where those methods are supposed to end up. In the `Model`? Or do we plan to move them to `Writer`?

cc @pjasiun @scofalik

**Comment by oskarwrobel** [comment]
`(insert|delete|*)content` uses `model.change` internally because they need to use writer instance. We wanted to avoid passing writer as param to top-level API because `model.change` takes care of it and we don't have to do it to keep the same undo step. But I understand the problem.

One way is to move each action that needs to be wrapped by `change` block to `writer`. The only way to get writer instance is to create change block so the problem will be solved. `Writer` will be the only API for changing model then, what seems to be not so bad. OTOH writer class will be large.

**Comment by ma2ciek** [comment]
It'd particularly solve my problem (https://github.com/ckeditor/ckeditor5-engine/issues/1212#issuecomment-354096160) and decrease tests complexity pretty much.

**Comment by pjasiun** [comment]
It makes sense to have the change block internally there. These are high-level methods on the model, what is pretty nice to explain: you can use our ready-to-use methods like `model.insertContent()`  or build your own custom change using `model.change`.

Also, note that the fact that one API requires change block and the other does not, is not a problem. It's not possible to make a mistake here. You can put `model.insertContent()` into `model.change` or `model.enqueueChange`, it is fine.  It also not possible to call writers methods without a change block, you will not get the `writer` class.
