### ISSUE TITLE
Selection should not retain attributes after parent block removal by an external change

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-engine#1267]
1. Go to http://localhost:8125/ckeditor5-link/tests/manual/tickets/113/1.html.
2. Take the 2nd scenario.
3. Write some text.

**Expected:**

The selection should not retain previous (`linkHref`) attribute. The whole editing context has changed and most likely users will not expect that.

**Actual:**

Still writing in the same link despite that it's parent `paragraph` has been removed from the model.

![kapture 2018-02-01 at 14 55 05](https://user-images.githubusercontent.com/1099479/35682150-f7720324-075f-11e8-8c15-ecb3ffb8b60a.gif)

Spotted in https://github.com/ckeditor/ckeditor5-link/pull/165.

**Note**: It's not about the link. Other attributes like bold, etc. are also retained.

**Comment by Reinmar** [comment]
This is weird. cc @scofalik @pjasiun

**Comment by pjasiun** [comment]
That's definitely a bug. This is because selection attributes are updated only as the result of selection operations:

https://github.com/ckeditor/ckeditor5-engine/blob/6d0c555c0a6da4e0aad9786aa50b6258bd8c51ad/src/model/documentselection.js#L486-L488

This makes sense for attribute define "manually". If I click the bold button I don't want to lose this attribute because of external change (which may even not touch my selection). It should, apparently, behave differently for attributes which are set based on the surrounding text. We already distinguish these types of attributes using the attribute `priority`.

BTW: attributes priorities should be better described, now it's hard to learn what some parts of the code do.
