### ISSUE TITLE
Two-steps caret movement when attribute starts at the beginning of block

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#1301]
Follow-up #1289.

Caret does not "leave" attribute element while moving left when text starts at the beginning of block element.

```html
<p><a href="">{}foo</a></p>
```

Pressing left arrow does not move selection before element `<a/>`.

**Comment by szymonkups** [comment]
Another issue:
1. Place selection at the end of the link.
1. Press left and right arrow keys couple times (enter and leave link using two-step caret movement).
1. Press left arrow to put selection inside link.
1. Try to exit link pressing right arrow.

Result: need to press left arrow key many times to exit the link.

![two-step](https://user-images.githubusercontent.com/2396463/37087220-f8d5370e-21f9-11e8-97f7-e6adb31e2d46.gif)

**Comment by Reinmar** [comment]
I've dug a bit more into the implementation of `restoreGravity()` and `overrideGravity()` and there are a couple of things which I found at least worth checking investigation:

1. `restoreGravity()` should log a warning when trying to go below `0`. It should also never allow going below `0`. It may also happen that situations when `restoreGravity()` is called more times than `overrideGravity()` happen so often that we should simply accept this situation (and don't log).
2. It's very odd that `overrideGravity()` only set the custom restore callback when `overrideGravityCounter == 1`. What if we called `overrideGravity()` more than once in a row?
3. I'm afraid that the automatic restore doesn't make sense. You can test it like this: add a console log in `change:range` callback added by `overrideGravity()`. Put your caret before link and then press right, left, right, left. Now, click somewhere else in the text. Console log will be triggered 2+ times. That's because these callbacks are never removed when you press left arrow key because left arrow key is handled by `bindTwoStepCaretToAttribute()` which also restores the gravity there. I think that it might be better if that util always handled restore manually.

I'm inclined now towards rewriting this logic with these assumptions:

* `bindTwoStepCaretToAttribute()` has its own flag whether it has just overridden gravity or not,
* `bindTwoStepCaretToAttribute()` should also take the responsibility to restore the gravity when needed,
* we completely remove the auto-restoring logic from document selection,
* we add some assertion logic for cases which should not happen and see if it helps to find bugs.
