### ISSUE TITLE
Unnecessary logic in Renderer#render()

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#1451]
After yesterday's [small refactoring in the renderer](https://github.com/ckeditor/ckeditor5-engine/commit/601f5f450c69000d4e6c1e2b2662528c8aa1154d) a CC dropped in the renderer:

![image](https://user-images.githubusercontent.com/156149/42084564-4dc97c28-7b8e-11e8-885a-3099318307a6.png)

The change I did yesterday was supposed to not touch any logic but apparently, it did. Namely, I think that `_updateChildren()` started rendering the filler itself. I tried to understand why it didn't render the filler previously but the code got complicated before the refactoring and I have problems tracking it down.

Anyway, it seems completely accidental that it didn't do it previously. According to the logic, `_diffChildren()` got the filler position as a param and so it was injecting filler into the `expectedDomChildren`. However, the `_updateChildren()` method didn't use the `expectedDomChildren` returned by `_diffChildren()` but another array which it created earlier... That array should also contain the filler, but maybe the duplication caused some problems. IDK. But the logic didn't make sense, for sure.

Now it seems that `_updateChildren()` and `_updateText()` always take care of rendering the filler by themselves. It seems logical that there's no need to render the filler in `render()` if these two functions took care of everything.

**Comment by Reinmar** [comment]
cc @f1ames

**Comment by Reinmar** [comment]
I'm analysing this comment for clues:

```
		// Check whether the inline filler is required and where it really is in the DOM.
		// At this point in most cases it will be in the DOM, but there are exceptions.
		// For example, if the inline filler was deep in the created DOM structure, it will not be created.
		// Similarly, if it was removed at the beginning of this function and then neither text nor children were updated,
		// it will not be present.
		// Fix those and similar scenarios.
```

**Comment by Reinmar** [comment]
>  At this point in most cases it will be in the DOM, but there are exceptions.

OK, are there?

> For example, if the inline filler was deep in the created DOM structure, it will not be created.

We fixed deep structure rendering recently, so most likely that's gone now. Will write a test though.

>  Similarly, if it was removed at the beginning of this function and then neither text nor children were updated, it will not be present.

According to the below code, after it gets removed, we then check if we need it again and if we do, we mark the children to be rendered. So the comment seems outdated too.

```js
		if ( this._inlineFiller && !this._isSelectionInInlineFiller() ) {
			this._removeInlineFiller();
		}

		// If we've got the filler, let's try to guess its position in the view.
		if ( this._inlineFiller ) {
			inlineFillerPosition = this._getInlineFillerPosition();
		}
		// Otherwise, if it's needed, create it at the selection position.
		else if ( this._needsInlineFillerAtSelection() ) {
			inlineFillerPosition = this.selection.getFirstPosition();

			// Do not use `markToSync` so it will be added even if the parent is already added.
			this.markedChildren.add( inlineFillerPosition.parent );
		}
```

**Comment by Reinmar** [comment]
Cool :) So I don't even have to write a new test. This one is good.

**Comment by Reinmar** [comment]
OK, @f1ames pointed out that I lost `withChildren: false` in https://github.com/ckeditor/ckeditor5-engine/commit/601f5f450c69000d4e6c1e2b2662528c8aa1154d#diff-4c87133ed830fc4ea0646426deba32cfR259.

Adding it back there indeed shows that the code which I've removed in #1452 was needed.

However, it means that we need a test which proves that `withChildren: false` is needed in that place. @f1ames I leave that to you. If you can figure out a test which proves that, then you can add it on master (together with the missing `withChildren` param. We cannot guess here.

**Comment by f1ames** [comment]
Just to add some insights here to show how the code works with `withChildren: false` and without it (default value is `withChildren: true`). The mentioned unit test starts with the HTML structure:

```html
<ul1>
    <li1>Foobar.</li1>
    <li2>FILLER[]<div></div></li2>
</ul1>
```

and then it moves `li2` inside new `ul` element (lets name it `ul2`) and places it inside `li1` resulting in:

```html
<ul1>
    <li1>
        Foobar.
        <ul2>
            <li2>FILLER[]<div></div></li2>
        </ul2>
    </li1>    
</ul1>
```

then `ul1` and `li1` elements are [marked to be rendered](https://github.com/ckeditor/ckeditor5-engine/blob/26673a0c8cd62244d9ccdb6967f50d4e0e47414d/src/view/renderer.js#L130). Now what happens during the `renderer.render()` call:

### `withChidlren: false`

1. The [`renderer._updateChildrenMappings()` method](https://github.com/ckeditor/ckeditor5-engine/blob/26673a0c8cd62244d9ccdb6967f50d4e0e47414d/src/view/renderer.js#L249) is called, nothing gets remapped here as there are no similar elements modified.
1. Then the [`renderer._updateChildren()` method](https://github.com/ckeditor/ckeditor5-engine/blob/26673a0c8cd62244d9ccdb6967f50d4e0e47414d/src/view/renderer.js#L555) is called for `ul1` element. As one of its children was removed (`li2`), the [`diff`](https://github.com/ckeditor/ckeditor5-engine/blob/26673a0c8cd62244d9ccdb6967f50d4e0e47414d/src/view/renderer.js#L567) results in `equal, delete` - `li1` stays in the DOM and `li2` is removed (here the inline filler is lost).
1. Then `renderer._updateChildren()` method is called for `li1`. Since its children has changed, the `diff` result is `equal, insert`. The `text:Foobar.` stays as it is and the whole `ul2` element is inserted<sup>1</sup><sup>2</sup>.
1. Finally, as inline filler is not present [it gets inserted](https://github.com/ckeditor/ckeditor5-engine/blob/26673a0c8cd62244d9ccdb6967f50d4e0e47414d/src/view/renderer.js#L221).

### `withChidlren: true`

1. The `renderer._updateChildrenMappings()` method is called, nothing gets remapped here as there are no similar elements modified. However, while [mapping `li1` element to DOM](https://github.com/ckeditor/ckeditor5-engine/blob/601f5f450c69000d4e6c1e2b2662528c8aa1154d/src/view/renderer.js#L259) also its children are mapped which detaches `li2` from the DOM<sup>2</sup> resulting in changing DOM structure to:

```html
<ul1>
    <li1>Foobar.</li1>
</ul1>
```

2. Then `renderer._updateChildren()` method is called for `ul1` element. As there is only one child as expected, the `diff` result is `equal` and no rendering takes place.
1. Then `renderer._updateChildren()` method is called for `li1`. Since its children has changed, the `diff` result is `equal, insert`. The `text:Foobar.` stays as it is and the whole `ul2` element is inserted. The `ul2` already contains inline filler as it contains whole DOM structured (`li2`) moved during mapping in the **1st step** above. 

---

<sup>1</sup> Here, the [mechanism inserting inline filler](https://github.com/ckeditor/ckeditor5-engine/blob/26673a0c8cd62244d9ccdb6967f50d4e0e47414d/src/view/renderer.js#L641) is not triggered as `filler.parent` is `li2` and `renderer._updateChildren()` method operates on `li1`.

<sup>2</sup> When converting elements from view to DOM, the element itself is [fetched from the mappings](https://github.com/ckeditor/ckeditor5-engine/blob/601f5f450c69000d4e6c1e2b2662528c8aa1154d/src/view/domconverter.js#L194). If it doesn't exists there [the new element is created](https://github.com/ckeditor/ckeditor5-engine/blob/601f5f450c69000d4e6c1e2b2662528c8aa1154d/src/view/domconverter.js#L217). The same happens to its children if `withChildren: true` option is present. New elements are created or existing ones are used. If the parent is newly created element and children exists in the DOM (like in the example above), DOM children are attached to a new parent. Since new parent is detached from the DOM, moved children also becomes detached.

**Comment by Reinmar** [comment]
@f1ames So, does the old `<li2>` gets reused in the `withChildren:false` case? Or do we create a new one?

The second question – if it gets reused, then is anything wrong with `withChildren: true`? Doesn't `withChildren: true` do the same thing, just earlier?

If so, do you think that it makes sense for `updateChildrenMappings()` to work like it works with `withChildren: true`. The method name may not be matching well this, but we kinda wanted to reuse as much of existing DOM as possible.

cc @scofalik

**Comment by f1ames** [comment]
> So, does the old `<li2>` gets reused in the `withChildren:false` case? Or do we create a new one?

With `withChildren: false` inside the `renderer._updateChildrenMappings()`, `li2` is not reused. It is removed and then whole `<ul2>` element is created. That's why inline filler needs to be reinserted.

> If so, do you think that it makes sense for `updateChildrenMappings()` to work like it works with `withChildren: true`. 

I'm really not sure about this. I stumbled upon this case at least two times in the past and it was quite confusing that the `DomConverter` was changing the actual DOM. True that it helps reusing existing DOM elements but still it doesn't fell right IMHO. And even though we reuse this part of DOM, it is still detached (when attaching to a new parent) and then attached to the DOM so the number of insert/remove operations on the DOM is the same (the only difference is that we do not create new DOM structure).
