### ISSUE TITLE
updateElementMappings does not refresh attributes

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1560]
This code:

https://github.com/ckeditor/ckeditor5-engine/blob/0821d9098b76c25fef577d6ccfe0c1324d0bc8ed/src/view/renderer.js#L317-L318

mark children of the remap element to be refreshed but do not map its attributes. It means that the DOM element may have old attributes after remapping.

**Comment by f1ames** [comment]
From the `renderer` perspective, there are no many options to distinguish if the element has some attribute modifications done in the meantime. However, all attribute changes, causes the element to be  marked to have its attributes updated by the renderer (`renderer.markToSync( 'attributes', node )` method). So the solution for this issue, apart from checking if new and reused elements are not similar is to check if new element was marked to have its attributes updated - if so mark the reused element.

**Comment by f1ames** [comment]
The proposed solution from https://github.com/ckeditor/ckeditor5-engine/issues/1560#issuecomment-425950993, assumed that the attribute will be firstly removed and then the element is removed itself:

```js
writer.removeAttribute( 'data-placeholder', viewP );

viewRoot._removeChildren( 0, viewRoot.childCount );
```

However, in opposite cases, when element is firstly removed and then its attributes removed:

```js
viewRoot._removeChildren( 0, viewRoot.childCount );

writer.removeAttribute( 'data-placeholder', viewP );
```

the `change:attributes` event will not bubble to the `viewRoot` (because removed element has no parent to bubble the event to) and element will not be marked to have its attributes removed (so the fix above will fail in this case).

If we would like to solve this issue in the renderer, the only way is to compare attributes between view and DOM element or just mark all replaced elements to have its attributes updated.
