### ISSUE TITLE
Fake Selection is Not Unbound when DOM Element is Unbound

### ISSUE THREAD

**Issue by kobsy** [ckeditor/ckeditor5-engine#1609]
I'm writing a plugin that allows encapsulating one widget within another. When the widget to be encapsulated is selected with a fake selection, the encapsulation would happen, but then the whole outer widget would disappear from the editor (though the elements were correctly arranged still in the model document).

What I believe is happening is that the renderer has recycled the `div` used to represent the fake selection to create the `div` of the outer widget, but `DomConverter._fakeSelectionMapping` never removed the `div` from its map. So when the engine goes to select the inner widget again after the inner has been moved to be a child of the inserted outer widget, it tries to use the recycled `div` -- now the outer widget -- to represent the fake selection again (assuming its first child is a text node, etc.), leaving things in an odd state. I _think_ the fix would be as simple as having the call to `DomConverter.unbindDomElement()` also remove the DOM element from `_fakeSelectionMapping` if it exists in the map, but I'm still learning my way around the code base, so I recognize there may be more to it than that. Thanks!

**Comment by Reinmar** [comment]
Yikes! We missed your ticket and PR. I'm really sorry for that. We'll review it this week.

**Comment by kobsy** [comment]
👍 Thanks 😁

**Comment by Reinmar** [comment]
OK, first of all, chapeau bas! That's not the piece of code I'd expect someone will be brave enough to dig in :D 

I've tried to understand the scenario that you described, but it's a bit unclear. What would definitely help is a [manual test](https://ckeditor.com/docs/ckeditor5/latest/framework/guides/contributing/testing-environment.html#creating-a-manual-test) (sample). If you could create one it would allow us reproducing this issue.

Without that, I had a look into the code, but I don't see how a retained fake sel contained could cause any issues. It's not used anywhere important. So, either I don't see something, or the problem is actually somewhere else :) Anyway, with a sample, we'll be able to debug it ourselves and verify it.

BTW, one more thing that I'd love to see is a higher-level integration test which would server as a regression test. This low-level unit test does not secure us from a similar bug to appear in the future because we will not remember why this was needed :)

**Comment by kobsy** [comment]
Thanks for taking a look at this. I've added a manual test to the PR #1610, as well as fixing one more issue that was surfaced when writing the manual test. I'll have to work on writing an integration test later this week, but hopefully this will help you to be able to investigate a bit more deeply on your end. 🙂

**Comment by Reinmar** [comment]
Huge thanks for the manual test. It's really helpful in understanding this issue.

The first thing I noticed is that it shows a pretty unconventional use of the nested editable. Usually, it'd be used inside a widgetized container element. You used it directly in the main editable. I don't think that using it alone should be causing any issues, but it might be worth checking just to be sure.

The other issue I spotted is that in some cases fake selection is not made at all:

![image](https://user-images.githubusercontent.com/156149/52425992-70daf100-2afd-11e9-8daf-fc28352d024b.png)

It happens for inline widgets (which are not supported yet, but we're working on it). We've stumbled upon this issue recently with @jodator and there's a PR which fixes it: https://github.com/ckeditor/ckeditor5-widget/pull/70. It'd be good to wait for that and see whether @jodator's PRs change anything in your case.

Once we have the above clarified and there are still some issues, I'm going to check your solution.

**Comment by scofalik** [comment]
Hi @kobsy!

I took a look at your PR and manual test again. It looks like with what is on current `ckeditor5-engine#master` all seems to work well. Could you please retest if the issue still occurs for you in your feature after updating `ckeditor5-engine` (you will probably need to set all repositories to the newest `master`)?

I've spotted one issue, though. When you have Special Char in Speaker if you click in a certain place (just below Speaker element), error from mapper is thrown. I've noticed that in the manual example you convert an empty model element to a non-empty view element. This is an incorrect approach, because there is no way to correctly map a position after the character in Special Char to a model position. That model position simply does not exist.

If you use similar conversion in your actual feature, please use [this custom mapping callback](https://github.com/ckeditor/ckeditor5-widget/blob/master/src/utils.js#L335). We wrote it very recently to handle some usual cases with inline widgets.

The other solution would be to have the text in the model element too.

**Comment by kobsy** [comment]
Hi! Sorry for the delayed response. I was finally able to circle back around and try the actual feature using the fixes on `master` (and subsequently with the recent release), and the issue does seem to be resolved with the use of the custom mapping callback.

I know that trying to map between an empty model element and a non-empty view element is not perhaps what was intended by the system, but I really appreciate that it's now possible with inline widgets, as it really was the easiest way to accommodate both existing data and existing presentation methods in our app. Thanks for all your hard work!

Since everything seems to be working now on `master`, I'll go ahead and close this issue.
