### ISSUE TITLE
Tests on engine are failing

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#1619]
After merging https://github.com/ckeditor/ckeditor5-engine/pull/1606 and https://github.com/ckeditor/ckeditor5-engine/pull/1613 tests on engine are failing.

**Comment by jodator** [comment]
There's an easy fix for this but it will require one method to be exported from `downcasthelpers.js` and such method should not be exported (as of #1556).

It is due to "catch-all" converters used in `getData()` function from `dev-utils/model.js`. I've removed the imports for:

1. `downcastDispatcher.on( 'insert' )` - was using `insert()` (which should not be exported #1556)
2. `downcastDispatcher.on( 'addMarker' )` - was using `insertUIElement()` (which should not be exported #1556)

As the first merge showed it will blow up or will be painful to maintain.

Right now I see two solutions:

**Solution 1:** Quick fix: private exports (exported private method is not something desirable I think) and use the `insert()` and `createUIElement()` in `getData()`.

**Solution 2:**
I was also thinking about some smarter way of fixing all above issues (dev-utils compatibility and not-exporting everything) and I was thinking about adding "catch-all" support for those helpers. In short it would allow to add `.markerToElement()` helper without specifing `config.model` in the converter definition. For such constructs it will add a converter for `'addMarker'`' event rather then `'addMarker:' + config.model` (see the `:` there) - used in here:
https://github.com/ckeditor/ckeditor5-engine/blob/49b8ad346f83b2989e15fc3d37554ad08a296735/src/conversion/downcasthelpers.js#L1038-L1039

Similar solution could be used for `insert` event.

cc @pjasiun

**Comment by pjasiun** [comment]
As we talked F2F exporting these methods as protected will be the best option.
