### ISSUE TITLE
attributeToAttribute upcast applies attribute recursively

### ISSUE THREAD

**Issue by joekaczmarek** [ckeditor/ckeditor5-engine#1662]
Trying to write a simple plugin that adds an attribute to a list item.

```javascript
editor.model.schema.extend('listItem', { allowAttributes: ['noteid'] });

editor.conversion.attributeToAttribute({
    model: 'noteid',
    view: 'noteid'
});
```

Downcast seems to work correctly, however when dealing with nested lists, upcast applies the attribute recursively.

Before upcast:
```html
<ul>
    <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">This
    <ul>
        <li>Is
        <ul>
            <li>A</li>
            <li>Test</li>
        </ul>
        </li>
        <li>Of
        <ul>
            <li>Functionality</li>
        </ul>
        </li>
    </ul>
    </li>
</ul>
```

After upcast:
```html
<ul>
    <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">This
    <ul>
        <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">Is
        <ul>
            <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">A</li>
            <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">Test</li>
        </ul>
        </li>
        <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">Of
        <ul>
            <li noteid="333cc167-cda1-40b7-b8b6-29fc48e5f4e2">Functionality</li>
        </ul>
        </li>
    </ul>
    </li>
</ul>
```

This would seem to be incorrect behavior based on the documentation for attributeToAttribute.

Plugin repo https://github.com/joekaczmarek/ckeditor5-id-list. Integrated in to the classic build at https://github.com/joekaczmarek/ckeditor5-build-classic-idlist-example (check out sample/index.html for a prewritten nested list with attribute).

Thanks!

**Comment by joekaczmarek** [comment]
All right, think I figured this out. I believe this is specific to lists, and how they are represented as a tree in the view but as a flat list with an "indent" attribute (depth, essentially) in the model.

When operating on a listItem with a new attribute ("noteid" in my case), the default toAttribute converter attempts to set the attribute on a model range that includes all of the sub items.

upcast-converters.js `_prepareToAttributeConverter`
```javascript
const attributeWasSet = _setAttributeOn( data.modelRange, { key: modelKey, value: modelValue }, shallow, conversionApi );
```

upcast-converters.js `_setAttributeOn`
```javascript
// Set attribute on each item in range according to Schema.
for ( const node of Array.from( modelRange.getItems( { shallow } ) ) ) {
    if ( conversionApi.schema.checkAttribute( node, modelAttribute.key ) ) {
        conversionApi.writer.setAttribute( modelAttribute.key, modelAttribute.value, node );

        result = true;
    }
}
```

`shallow` is set to true here, but has no effect since in the model all listitems are siblings.

The root cause here might be some issue with how modelRange is set and then passed to the toAttribute converter for my custom attribute. I don't know the code well enough to understand what modelRange needs to be set to for other features to work properly.

I solved my problem with the following:

```javascript
editor.conversion.for('downcast').add(downcastAttributeToAttribute({
    model: 'noteid',
    view: 'noteid'
}));

editor.data.upcastDispatcher.on('element:li', (evt, data, conversionApi) => {
    debugger;
    if(conversionApi.consumable.consume(data.viewItem, { 'attributes' : ['noteid'] })){
        const listItem = Array.from(data.modelRange.getItems( { 'shallow' : true } ))[0];
        const noteId = data.viewItem.getAttribute('noteid');
        conversionApi.writer.setAttribute('noteid', noteId, listItem);
    }
});
```

Probably a better way to write this, but it seems to work.

**Comment by joekaczmarek** [comment]
Looks like #1672 discusses some confusion around what modelRange should be.

**Comment by Mgsy** [comment]
Hi, @joekaczmarek! Sorry for a late response, somehow we missed your ticket. We're glad that you've managed to solve the issue.

**Comment by joekaczmarek** [comment]
@Mgsy I think there's likely a bug here. Doesn't seem correct that `editor.conversion.attributeToAttribute` has an asymmetry between downcast and upcast behavior.

**Comment by Mgsy** [comment]
@jodator, could you take a look at this one?

**Comment by scofalik** [comment]
Hi @joekaczmarek.

First of all, good job on cracking down the issue, it is as you wrote. As you noted, because of how lists are represented in the model and in the view, it is impossible to use helpers to convert `<li>` attributes.

Your solution went into a good direction. I was thinking about upgrading it but, actually, if you consider weird edge cases, it looks quite bullet-proof. The only problem you could run into is if the first `<li>` would get broken due to loading some "incorrect" HTML:

```html
<ul>
    <li customAttribute="foo">
        Foo
        <p>Xyz</p>
        Bar
    </li>
</ul>
```

But it is a minor issue.

Also, keep in mind, that you can use `editor.conversion` even for custom converters. This way you don't need to get a reference to a proper dispatcher.

```js
editor.conversion.for( 'upcast' ).add( dispatcher => {
    dispatcher.on( 'element:li', ( evt, data, conversionApi ) => {
       // ...
    } );
} );
```

> I think there's likely a bug here. Doesn't seem correct that editor.conversion.attributeToAttribute has an asymmetry between downcast and upcast behavior.

It's not really a bug. `data.modelRange` is set correctly, and should be set on all inserted items due to other scenarios. It is really more connected with how lists work and how `data.modelRange` is unfit for this flat/tree conversion style.

The `data.modelRange` whole mechanism maybe could be improved to give converters possibility to mark inserted content more precisely but this would mean huge and breaking changes, which is probably not worth at the moment. We might look at it in the future, but certainly this wouldn't be our priority at the moment. OTOH, we could introduce some helpers to make writing list-connected features easier.

**Comment by joekaczmarek** [comment]
> data.modelRange is set correctly, and should be set on all inserted items due to other scenarios.

Ah, yeah this is the part I don't have much of a grasp on. Thanks for the response!
