### ISSUE TITLE
Model visual debugging tool

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#170]
To make working with the tree model simpler we need some debugging tool, which will let developer show the whole structure in the most readable way. The tool needs to be cross-browser.

**EDIT by @Reinmar:** See the specs for this tool in https://github.com/ckeditor/ckeditor5-engine/issues/170#issuecomment-413537429

**Comment by Reinmar** [comment]
Tools created for https://github.com/ckeditor/ckeditor5-engine/issues/306 may help temporarily. We'd just need to add some nice formatting options and it will be enough for a while.

**Comment by pjasiun** [comment]
Tool @pomek created as a part of the hackathon do the job: https://github.com/ckeditor/ckeditor5-hackathon/tree/graphical-model-representation All we need is to port it to the master as a testing tool.

**Comment by Reinmar** [comment]
Porting is one thing. Finishing is another – that tool doesn't print element attributes nor the selection.

**Comment by Reinmar** [comment]
## Why it's needed?

CKEditor 5's model and views are abstract structures which people are not familiar with. Especially the model is tricky to grasp because its structure is different than that of the HTML (DOM). We often see developers trying to write plugins without understanding what's the structure of the model, what elements are there and how they relate to what they see in the DOM. That must be frustrating and confusing for them because it's like writing plugins for a black box. We must change this.

## Plug and play

This tool should be super easy to use with any editor running on any page, JSFiddle, etc. It must be easy to plug without building anything and without changing anything in an editor. What's more, it should not only be easy to initialize, but it should also automatically render itself on the page.

Naturally, this tool will be useful for us too but it's our first goal to enable it for other developers. Therefore, I think that it should be available via our CDN. So, e.g. when you work on something on JSFiddle or in your app you need to:

1. Add `<script src="https://cdn.ckeditor.com/ckeditor5/[version.number]/viewer/ckeditor.js">`
2. Run `CKViewer.start( editor )`

And that's it. It should appear on the page and should be fully functional, styled, etc.

## Implementation details

* It needs to be versioned together with the editor so developers are always able to use a version compatible with the build/editor they use. That's why I proposed exactly the same CDN URL format as to builds. In some sense, this will be a build, just not an editor build.
* There are more similarities to builds. It will also require to be rebuild before publishing (it can be available via npm too). However, unlike builds, it must have **zero dependencies** to CKEditor 5. Since it must work with any editor, it must work based solely on the public API.
* I think that we may or even should use React or Vue plus perhaps CSS libs to build it because it may be more encouraging to further extend it. Also, the whole thing needs to be build to a singe JS file, so at least webpack is highly justified. This all means that it becomes a project itself, but I'd keep it within our dev env so the tool is also always available to us too. That, in turn, means that it should be build and committed with every (significant) commit, so you don't have to do anything to use it (except importing it).
* During releasing we'll have to remember that it must follow the version of `ckeditor5`. That, most likely, it's easiest to do manually.
* It should be build to an UMD format.

## Features

MVP:

* Automatically render on an existing page without affecting its layout. IDK which viewport side to choose initially – perhaps bottom cause then there's the biggest chance that you'll be able to scroll the page to see the editor which you want to investigate.
* You must be able to hide the viewer (cause it's going to cover at least 50% of the page).
* It may be worth to check whether there's a tool for showing a dockable element, with resizing, hiding, viewport side choice features. That would help a lot if we didn't have to reinvent the wheel.
* I imagine the UI build around tabs. Just like in the browser's dev tools.
* The bare minimum of tabs:
   * Model tree viewer. Static, no folding, no selection, nothing. Just elements, text nodes and their attributes.
   * Editing view tree viewer. The same basic form as in the model tree viewer.
   * Data view tree viewer. The same as above. (Note: this tree is not live, so perhaps a "refresh" button would be needed or a change-based automatic refreshing).

Next steps:

* Allow controlling the viewer's size and position (docking).
* Initially, you'll be able to show just one tab at a time, but I think that in the future it would be useful if you'd be able to see the model and the view at the same time. That might be achieved in multiple ways but perhaps it'd be easiest to allow splitting the view of the viewer into two columns where in both of them you'd have the same set of tabs to choose from. Then, you'd be able to choose the model tab in the first column and the view tab in the second column.
* More tabs and ideas:
   * Schema viewer.
   * Commands viewer – list of commands + their `is*` properties + "execute" buttons (not sure if doable cause command params).
   * Show the selection (and its attributes) in the model and editing views.
   * Blink in the right trees place when something changes.
   * Make trees foldable.
   * Add event viewer. E.g. a list of some most popular events that you can select using checkboxes and then they get automatically printed to the console. That could be useful for quickly tracking focus, etc.
   * Editor state viewer – list of most important editor props.
   * Something for conversion?
   * Display more info about offsets of nodes in the tree (e.g. after hovering them).

**Comment by Reinmar** [comment]
Actually, it's not an engine's tool any more so I'm moving this to ckeditor/ckeditor5.

**Comment by Reinmar** [comment]
Moved to: https://github.com/ckeditor/ckeditor5/issues/1205
