### ISSUE TITLE
Method schema#getAttributeProperties() should always return an object

### ISSUE THREAD

**Issue by mlewand** [ckeditor/ckeditor5-engine#1717]
## Is this a bug report or feature request?

🐞 Bug report

## 💻 Version of CKEditor

CKEditor v5 @ 12.0.0

## 📋 Steps to reproduce

```
conole.log( schema.getAttributeProperties( 'my-fancy-nonexisitng-attr' ) );
```

## ✅ Expected result

Logs: `undefined`

## ❎ Actual result

Should log empty object: `{}`

**Comment by jodator** [comment]
I wonder why we must return an object? AFAIR there is a case of failing early in some setups.

Other APIs will return `undefined` for similar cases:

- `editor.config.get( 'foo.bar.baz' )` will return `undefined`
- `editor.model.schema.getDefinition( 'fooBarBaz' )`  will return `undefined`

So I'd rather double check this requirement with @pjasiun.

**Comment by mlewand** [comment]
There are two main benefits:

* It simplifies developer experience, see https://github.com/ckeditor/ckeditor5-remove-format/blob/7ec56a7e380ff39294d096b746138f47998b9db9/src/removeformatcommand.js#L96 - with this change you don't have to worry about missing value, and just proceed with `if ( schema.getAttributeProperties( attributeName ).isFormatting ) {` (main reason)
* Without this improvement there's a potential for making references to undefined value.

**Comment by pjasiun** [comment]
Yea, that's tricky. I agree with @mlewand's arguments, but that also true that so far returning `undefined` when there is no value is a standard in the project.

`editor.config.get( 'foo.bar.baz' )` is not the best example because since it can return various types we can not use an empty object as the default value. However, `editor.model.schema.getDefinition` is much better example. 

We also have functions like `getSingleTextNodeChange( mutation )` which returns object or `undefined` even though it could allways return object.

Fortunatelly I was not able to find many places which return `{Object|undefined}` or `{Array|undefined}`. Note that `{SomeInstance|undefined}` or `{String|undefined}` are usually a different case, since `undefined` has usually a semantic value there.

We might have a rule that as long as there is no semantic difference between returning empty array/object or `undefined` we prefer returning empty array/object to improve development experience.

Anyway, I think that if our API will be inconsistent it will be the worst option because developers might expect that empty object will be returned and get `undefined` what will cause errors. This is why I think that to close this issue we should check the whole API or create a follow-up to do so soon (fortunately it is not such a big task).

**Comment by jodator** [comment]
> Fortunatelly I was not able to find many places which return `{Object|undefined}` or

Other places might not be well documented though...

**Comment by pjasiun** [comment]
> > Fortunatelly I was not able to find many places which return `{Object|undefined}` or
> 
> Other places might not be well documented though...

That's true. `getDefinition` was not well documented too. However, I don't think we should care that much about not documented parts. As long as we agreed about some rules we will fix all not documented places later, when we will find them.

**Comment by pjasiun** [comment]
Them most important think is to have the rule, and fix places we know about. We should avoid having different rules for different parts of the code.

**Comment by jodator** [comment]
I was trying to quickly find some references for this problem:

1. https://stackoverflow.com/a/1626620/2273046 (for nulls)
2. https://python-patterns.guide/python/sentinel-object/ (for sentinel objects)

Probably there are more votes for both approaches and we should pick & stick to one.

With arrays/list it's easier - you should always return empty array/list in such cases.

When method is returning an object (like here) we might either return `undefined` to indicate that such attribute is not defined/has no definition or return sentinel object to make DX easier.

For other cases we might think `String|undefined` - might depend on context.

**Comment by pjasiun** [comment]
I think that the rule should be:
1. If there is no semantic difference between an empty object, string or array and `undefined`, we should use an empty collection. For instance, if you get mutations and there are no mutations, you can use an empty array.

2. If there is a semantic difference we should use undefined. For instance, if you get selected text in the editable, but the selection is in a different editable, then `undefined` should be returned.

I think it is the matter of the compromise between not hiding errors and useful API.

For `getDefinition` it makes sense to return an empty object.

**Comment by pjasiun** [comment]
Note that for this reason, to make the API simpler, we make the model selection always return something even if the real selection is not set yet.

**Comment by mlewand** [comment]
It fits well semantic usage. The API client asks for attribute properties - a feature provided by our API. It is our responsibility to make the returned value usable and correct.

Also there's no point in differentiating whether _any_ attribute's property was set or not.

@pjasiun @jodator do we have anything else to clarify regarding this?

**Comment by jodator** [comment]
@pjasiun I think that we agreed that in this case you may always return object.

But we probably need a follow-up ticket to review other parts of an API, right?

**Comment by pjasiun** [comment]
Yep. That's basically my point.
