### ISSUE TITLE
Range with root

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#285]
Because the range can not start before the root element, we created special operation and delta to change attribute on the root. It is fine as long the logic can be hidden in the model classes, but unfortunately it affects also conversion.

It is not possible to have the same `change` event for the changes on the root and other changes, because regular attribute change event contains range and root attribute change event contains root element. It affects conversion badly.

We think about making node list iterable (https://github.com/ckeditor/ckeditor5-core/issues/284), so maybe list of roots should be a node list.

**Comment by scofalik** [comment]
In #284 we will introduce `DocumentFragment`. It will enable us to use `treeModel.TreeWalker` on nodes that are detached from the Document tree but should be considered as siblings (so this is same as in DocumentFragment in DOM). Right now we have `treeModel.NodeList` but it doesn't have useful iterating tools as nodes in `treeModel.NodeList` are not required to have same parent.

One of ideas to solve this issue is described below:

After #284, `treeModel.Position` will take as root either `treeModel.RootElement` or `treeModel.DocumentFragment`. To solve this issue, we will have to go step further:

1. We will remove `treeModel.RootElement` class.
2. `treeModel.Position#root` will be either `treeModel.DocumentFragment` or `treeModel.Document`.

Making `treeModel.Document` a root of ... all roots ... we will achieve a few things:

1. Deltas and operations will be able to operate on roots. This is mostly for mentioned `(Root)AttributeDelta` but we are also thinking about removing and adding roots in the future. It will work out-of-the-box because `treeModel.Document` will implemented API needed for `treeModel.TreeWalker`.
2. Because there will be one entry point to the Document (`treeModel.Document` is THE root), we won't have to synchronize different roots when sending operations to Collaborative Editing remotes. This means that we will only send paths with positions.

There are also issues:

1. We have to think of a better name for what now are `treeModel.RootElement`s. We still need to differentiate those elements and be able to get them by an id, not only position.
2. We have to make sure that we don't mess with *graveyard root*. Graveyard will probably be always a root with 0 index and all batches/operations will have to check whether they do not operate on graveyard in a wrong way (i.e. for moving stuff to graveyard we have `RemoveOperation` so normal `MoveOperation` should not be used in such manner because that might mess up OT). We will have to think about it.

**Comment by pjasiun** [comment]
> We have to think of a better name for what now are treeModel.RootElements.

We may call them `Regions`. These are similar to what UI call `Regions`.

**Comment by pjasiun** [comment]
Or `EditableRoot`.

**Comment by pjasiun** [comment]
This is outdated after the engine refactoring. Now change event is not fired after each operation and all changes are done by operations so problems described above disappear.
