### ISSUE TITLE
LiveRange's positions drift in wrong direction when inserting content next to it

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#340]
I've got selection like this:

```html
<p>fo<selection /></p><p>ar</p>
```

After merging those two paragraphs using merge delta I get:

```html
<p>fo</selection>ar<selection></p>
```

I think that collapsed range's should have both positions with the same stickiness. Or even better - left pos should equal right pos.

**Comment by Reinmar** [comment]
I've hit this issue again with:

```
// '<p>x</p><p>foo<selection /></p><p>y</p>'
const pos = selection.focus;

batch.split( pos );

selection.collapse( pos.parent.nextSibling );
```

Expected:

```html
<p>x</p><p>foo</p><p><selection /></p><p>y</p>
```

Actual:

```html
<p>x</p><p>foo</p><p></p><p><selection />y</p>
```

I think that we should fix this ASAP, cause I need to workaround this in nearly all algorithms.

**Comment by scofalik** [comment]
I've faced this issue and changed this behavior already on one of my branches. I'll try to make PR of it ASAP.

Initially I also thought that when position is collapsed we could swap stickiness but this may lead to some weird cases when you insert nodes at the same position as collapsed live range. Then all the nodes end up in the live range and I don't think this is something people would expect as default behavior. What I did is setting stickiness to NEXT, so live range ends up collapsed after insterted nodes.

But I am open to discussing this. The fix is very small and from what I've seen it does not break any tests (at least not on my branch).

**Comment by scofalik** [comment]
Take a look at #389 and #392 and see if your case works with fixes on that branch / from that PR.

**Comment by Reinmar** [comment]
Should be fixed by #392. I'll assign this ticket to myself to check it later.

**Comment by Reinmar** [comment]
Idea: stop rendering the selection if it hasn't changed after the last rendering.

**Comment by Reinmar** [comment]
I can see that there's a test for that in https://github.com/ckeditor/ckeditor5-engine/commit/82711724679c316469b6d9510c6799dd1d51afa3 so we can close it.
