### ISSUE TITLE
Rename to TreeWalkerValue.(previous|next)Position to positionAfter and positionBefore

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#345]
I'm always looking for those names there. Always the same mistake. I think that that's due to `Position.createAfter()` and `positionBefore()`.

**Comment by pjasiun** [comment]
This is because `(previous|next)Position` is not necessarily the same as what `Position.createAfter()` or `createBefore()` returns. If you enter element `nextPosition` will be inside that element, with offset 0, but `Position.createAfter()` will be after that element. The same with `previousPosition`/`createBefore` and leaving element.

**Comment by Reinmar** [comment]
The tree walker works in a source order and pays attention to tag openings and closings as you would see them in the source, not in the tree. So IMO it will be ok if we call these `positionBefore` and `positionAfter` cause that's how you think about the content you're iterating over.

**Comment by Reinmar** [comment]
It's like this for years, so let's keep it.
