### ISSUE TITLE
CharacterProxy: Do we need it?

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#353]
This issue is to make a research and, if possible, get rid of `CharacterProxy` which becomes more and more similar to `TextProxy`. Maybe it would be enough to just have `TextProxy` instances (some of them of length `1`).

**Comment by Reinmar** [comment]
Could you explain why we needed any of those? :D

**Comment by scofalik** [comment]
Because we want to keep characters as single nodes but don't want waste too much memory and processing power to handle each character seperately. We've come a long way since the initial concept to this stage...

**Comment by pjasiun** [comment]
I think that the simplest explanation is the case when you start your range inside a middle of the text. You want walker to return that part of the text, with attributes and methods, but you can not split text during iteration. So you get `TextProxy` which represent only that part of the text you have in the range.

**Comment by pjasiun** [comment]
And, since we changed `Walker` so now it return text by default, instead of characters, `TextProxy` became a primary class. Returning characters is option now, a special case, so it makes sense to return `TextProxy` with length `1`, do not keep dedicated class for special case.

Also we could consider changing `Writer` so the type would be `TEXT` for both `TEXT` and `CHARACTER`.

**Comment by pjasiun** [comment]
Also we could rethink `Text` vs. `TextProxy` separation, and having one class may appear to be better. For sure current situation with `Text`, `TextProxy`, `CharacterProxy` and `NodeListText` seems to be overcomplicated.
