### ISSUE TITLE
Check if the operations are added and applied in the proper order.

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#386]
For deltas which are added to batches we need to apply operation right after adding it to the delta. Otherwise it will not be possible to check if it is a new delta, and we will have very ugly, deeply hidden bug. 

There should be a check on `applyOperation`: if delta, we are adding operation to, is added to the batch then the operation we apply should be the last operation in this batch. Throw error otherwise.

**Comment by scofalik** [comment]
This issue is incorrect. Deltas created through operational transformation (collab editing, undo) are created whole at once. It will require doing some stupid things to get around this. It will really hurt me if I had to create new delta, move operations to it one-by-one and apply them in between. This is hacking.

The truth is that we need to treat deltas as the lowest unit we operate on, see #500. Then we will not need to do stupid things, and we will not care about stupid bugs.
