### ISSUE TITLE
Changes required to transfer operations

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-engine#395]
To transfer some changes from one editor to another one would have to listen on document for:
- `change` event to collect applied deltas
- `changesDone`  event to transfer changes to another document.

As for now I cannot take deltas from batch.

**Comment by Reinmar** [comment]
Are you sure you have to wait for `changesDone`? Can't you sent them immediately?

**Comment by jodator** [comment]
As @pjasiun said they might be doubled in subsequent event.

**Comment by Reinmar** [comment]
WAT? Could you elaborate on that?

**Comment by pjasiun** [comment]
The problem is that `change` event is fired with every operation. What we want to send is a delta with all operations. Unfortunately there is no way to check if delta in the change event is complete. For instance if delta has 2 operations, change event will be fired twice, every time operation is added to the delta and the first one will have incomplete set of operations in the delta.

Fortunately, `changesDone` is fired synchronously when all deltas are applied. It seems to be a good moment to send changes, since we know that all deltas are complete at that moment.

**Comment by fredck** [comment]
No chance to have a "delta" event, right?

**Comment by jodator** [comment]
As discussed the "delta" solution isn't necessary since we have both 'change' and 'changesDone' so no additional coding is needed (for getting deltas). The 'delta' event as I understand would have to be implemented in batch (which does not fires event at this time).

**Comment by pjasiun** [comment]
We would need to mark deltas as "done" to know when we have to fire an event. It is doable and we even were thinking about it, but since we realised everything can be done without introducing additional event, we agreed there is no point in introducing more events. 

Also "delta" event might be useful only for the collaboration editing. Other plugins do not care what delta each operation was part of. This information is useful only for OT, AFAIR.

**Comment by scofalik** [comment]
What is the status of this issue? And also are you sure you are right? I don't think that `changesDone` means that delta is complete. Say you have a delta with two operations, and you do:
```javascript
delta.addOperation( operationA );
document.applyOperation( operationA );
delta.addOperation( operationB );
document.applyOperation( operationB );
```
This will happen:
1. Operation A will be executed.
2. During execution, some changes will be enqueued.
3. Those changes may trigger other changes.
4. After all changes are done, `changesDone` is fired.
5. Operation B is executed.

What you really need is something like described in #500. However, as mentioned in the issue, there are some disadvantages of applying whole delta at once, so this needs to be discussed. I, for one, am for applying whole delta at once.

**Comment by jodator** [comment]
I'm not sure if this is done properly.
It is done to have this working in the state of engine when it was implemented.

What I need is to have event/callback/email that notify me that some changes are ready to transfer from one document to the other.

AFAIK there is no mechanism right now to take deltas/operations after all changes are done.

**Comment by scofalik** [comment]
Okay, I thought it through. `changesDone` can be used to see whether delta is already done, because all operation done in that delta are in one enqueue block. This means that when changes are done all operations from that delta are also applied.

**Comment by jodator** [comment]
I think that this ticket is not valid anymore. One can iterate over `batch.deltas` anyway.
