### ISSUE TITLE
ModelToView#convertInsert() needs to be renamed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#437]
First of all, it should be `convertInsertion()`.

However, that name would still look weird. E.g. in the data controller we'd have a line like:

```js
this.modelToView.convertInsertion( modelRange );
```

It sounds like the insertion already happened and now we need to convert it. Even if in some sense that's true, perhaps we could find a better name. E.g. the dispatcher is meant to trigger the insertion conversion, so perhaps something like `fireInsertionConversion()` would fit better.

**Comment by pjasiun** [comment]
The original idea for these method was that it will convert model change. Something was inserted to the model, and now this insertion, which already happened, should be converted to view. Usage of if in the `DataController` was hacking.

But since the method is more useful then only converting model insertion it makes sense to rename it, so the name will fit all usage. I think that, because the class is called dispatcher we could call it: `dispatchInsertion`.
