### ISSUE TITLE
Model parse( '<paragraph></paragraph>' ) returns RootElement

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#441]
`model.parse( '<paragraph></paragraph>' );` returns `model.RootElement` with a `<paragraph>` element as a child.

Expected results are `<paragraph>` element, or `DocumentFragment` for multiple elements. There is no way `model.parse` should return `RootElement`.

I spend too much time debugging code because of this bug.

**Comment by szymonkups** [comment]
For now there is no way to place selection inside model's `DocumentFragment`, so `parse()` method cannot use it when selection is present in parsed string. It is because selection uses `LiveRanges` which are listening on document `change` event. `DocumentFragment` is not connected with any document so it is not possible to place selection there.

**Comment by pjasiun** [comment]
I am not sure if `parse()` should return `Selection` then. That is true that `Selection` is a set of `LiveRange`s, but `LiveRange` needs `Document` to work, and `parse()` is document-independent. It again makes sense to introduce Static Selection proposed here: https://github.com/ckeditor/ckeditor5-engine/issues/329 It is what `parse()` should return. Than Static Selection should work fine on Document Fragment, since (Dead)Positions work fine with `DocumentFragment`.

**Comment by Reinmar** [comment]
Let's not work on this now. Sounds like a chain of things to fix :D.
