### ISSUE TITLE
#isFocused should be moved to EditableElement

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#448]
Each editing host (an element with cE=true/false), either editable or not, can be focused or not, hence the property should be moved from RootEditableElement to EditableElement. The focus observer will need to be updated as well.

**Comment by pjasiun** [comment]
Surprisingly, not that simple. `isFocus` is now binded to the document, but when `EditableElement` is created it does not have document reference. It can take it from the parent, but it is assign to the parent later. And it is not enough to observe `parent` property, because the parent can have not yet his parent... I love how trivial task can become more and more tricky...

**Comment by Reinmar** [comment]
Fixed by #451.
