### ISSUE TITLE
InsertOperation should deeply clone passed nodes.

### ISSUE THREAD

**Issue by jodator** [ckeditor/ckeditor5-engine#473]
The problem is that NodeList have references to the same nodes.

As a result getting history of simple type operations duplicates text - found in classic editor.

Test Scenario I:
1. Type abc into empty editor (only with `<p></p>` inside).
2. Get deltas from `document.editor.history`

Result:
- first delta's operation reference whole text "abc" instead of "a" only

Test Scenario I:
1. Type abcd into empty editor (only with `<p></p>` inside)
2. Place cursor between b and c ( ab|cd )
3. Press enter key
4. Get deltas from `document.editor.history`

Result:
- last delta (SplitDelta) has two operations:
    - insert operation of a paragraph with text nodes ("cd")  - a probably bug
    - move operation of text nodes "cd" inside a new paragraph

**Comment by scofalik** [comment]
In second case it's not really a bug (if I understand correctly).
The `SplitDelta` has an `InsertOperation` of `paragraph`. When the delta was created the `paragraph` was empty and only after it got its children. I am not sure right now but AFAIR we need to reference the original node to have *something* working correctly. But as I wrote, I am not sure now.

The first case is interesting though.

We will have to look into it because this is a difficult problem.

**Comment by jodator** [comment]
The socond case is bug in case of collaborative editing - when appling the same deltas on a different document you get:
```
ab
cdcd
```
and you get mismatch of data from both editors.

Also any reference to a node that can change later can result in collaborative editing mismatch.

**Comment by pjasiun** [comment]
Fixed by #537.
