### ISSUE TITLE
Clean view after manual changes

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#484]
View changes does not need to come from model. By design, it should be possible to add view representation of the element which have a different model, or is a view-only feature, for instance a selection of another user in collaboration editing.

Adding attribute elements manually seems to work fine. They, also, do not break changes which comes from model. Unfortunately changes which come from the model can break manual changes. Attribute elements can be split, merged or moved. It means that the references to these elements can be lost, or new attribute elements can appear with no references saved.

There should be a way to handle it. The simples solution is to remove all changes applied manually on each change event and reapply them. Still there should be a tool to make it simpler. Now removing this changes is not that simple, because `writer.unwrap` expected the range to start and end in the same container.

Later we could bring more tools for manual view manipulation. For instance `writer.wrap` and `writer.unwrap` could work on any ranges.

**Comment by scofalik** [comment]
This came up when I was working on selective undo highlightning. It should be fairly easy feature, assuming that I already have transformed `ModelRange` which just has to be represented in the view.

As you said, setting something in the view is not difficult (well, it is because `writer.wrap` needs "flat" range) but clearing after is painful. Most difficulties come from the view that changed. The "workflow" for maintaining your custom out-of-the-model view changes is usually as follows:
- you have position/range/element in model
- you transform it to view position/range
- you apply some custom changes near that view position/range
- if you `writer.wrap` something, you need to store view range returned by that method and use it later to clean your changes.

Often times model position/range is useless when you want to clear your changes, you need to remember view position/range/element. Since view could change, they might be useless, especially, as you mentioned, wrapping is the most difficult (if you just inserted an element, you can store it and it will be valid even if it moved).

One thing that I forgot during hackathon was that there is `viewCleanup` event. I wonder if using that event helps. It is fired before model-to-view conversion. We could plug in cleaning code before any changes from model invalids our stored view ranges/positions. This still won't save us from other plugins doing custom things in view. But maybe we could come up with some kind of "best practices" or workflow that will minimize the amount of possible errors (just like we did with `enqueueChanges` which has, after all, similar purpose).

**Comment by pjasiun** [comment]
> As you said, setting something in the view is not difficult (well, it is because writer.wrap needs "flat" range) but clearing after is painful.

This should be improved too.

> if you `writer.wrap` something, you need to store view range returned by that method and use it later to clean your changes.

`writer.wrap` is not that big deal. `writer.breakAttributes` is a bigger problem, because it creates a new element and is called every time selection changes.

My first idea was that `AttributeElement` have a `tracker` property and whenever it is cloned in adds new instance to the tracker, so the `AttributeElement` can track itself. But I do not like it, class should not track itself, someone else should track `AttributeElement`. So maybe some tool.

Then I realised that it is `writer` who handle `ContainerElement`s and `AttirbuteElement`s, it is `writer` who `wrap` or `breakAttributes` and creates all the mess, so it could be writer who track occurrence of an attribute and be able to remove all of them.

**Comment by Reinmar** [comment]
I think this is mostly taken care of now.
