### ISSUE TITLE
Delta transformations: compose delta

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#486]
In deltas transformations we have this problem, that a delta, when transformed, might be transformed using "default algorithm" which just uses the default OT mechanism and transforms all operations from one delta by all operations of another delta.

Unfortunately this may cause spliting an operation into two and the delta loses it's original composition. 
I.e. `SplitDelta` from `InsertOperation` and `MoveOperation` becomes `InsertOperation`, `MoveOperation`, `MoveOperation`. Then, it is difficult to transform it using "special case algorithms".

My proposition is, instead making deltas with weird composition, create more deltas. I.e. `SplitDelta` could become `SplitDelta` + `MoveDelta`. `MoveDelta` could become multiple `MoveDelta`s. We would just need a clever way of composing deltas, but this should not be so difficult. Each delta could have static `compose` method that would take an array of operations and will return an array of deltas where first delta has same type/class and other are "complementary" deltas.

Anyway, we need some kind of enchancement in this regard, because right now deltas transformations are not in the best shape and will break in more complex cases. I think this is the best solution I came up with.

**Comment by pjasiun** [comment]
👍  Same way operation can become 2 operations after the transformation, delta should be able to return 2 deltas.

**Comment by Reinmar** [comment]
I've just talked with @scofalik to gain some understanding of what needs to be done still. There are two points:

1. Splitting deltas into pieces. This is only needed if we'll start using wrap/unwrap + move. So far we don't use it and the only case I can see now is blockquote support. We'll be fine if it's implemented without any special handling for cases like wrapping + something weird. In fact, wrapping conflicts with move or split. We don't do any moves right now, so that's fine. And we won't split the parent node of a range which is being wrapped, because we don't create such deep structures. So all this should work on based on basic OT.
2. What remained (before v1.0.0) is tests+stability improvements.

**Comment by scofalik** [comment]
This already has been done in recent OT refactor. We have deltas normalization now.
