### ISSUE TITLE
Editable loses and regains focus when typing

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#512]
1. Open http://tests.ckeditor.dev:1030/build/amd/tests/editor-classic/manual/classic
2. Init the editor.
3. Start typing.

See that on each letter isFocused is set to false and then back to true.

**Comment by pjasiun** [comment]
This is because editable `isFocused` is bind to `selectedEditable` (https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/editableelement.js#L53-L59). Every time letter is typed we convert model  selection to view. During the conversion we remove all ranges and add new, so the `selectedEditable` became `null` for a moment.

We should not fire `change: selectedEditable ` every time selection change, so this code should be changed: https://github.com/ckeditor/ckeditor5-engine/blob/4f873fbeff64e35638f7eaec1fc4d4fa2bb8e695/src/view/document.js#L98

The question is how to synchronise `selectedEditable` changes. Disable events during the conversion? In might not be enough. With render? It might be not often enough. Tricky.

**Comment by pjasiun** [comment]
We could fire `change:selectedEditable` and `change:isFocused` on `render`. It might solve the problem with synchronising UI with the view.
