### ISSUE TITLE
Inconsistent errors naming

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#527]
We have a problem with errors naming consistency in the engine. Some errors are named with namespace prefixes, i.e. `view-selection-range-intersects` in `view/selection.js`, others do not have that prefix i.e. `position-after-root` in `view/position.js` or most (all?) things in model.

We should decide whether we want to add those prefixes or not and refactor code accordingly.

**Comment by Reinmar** [comment]
I think we'll not be able to define some strict rules and we should not try to. It's going to be the getters/properties battle again. I'd follow common sense in all cases. In this one adding view/model denominator for every error code sounds good.

**Comment by scofalik** [comment]
I do not want to have a complex rule here. Right now error names follow more-or-less this convention:
`<className>-<methodName>-<errorCode>` where `errorCode` is two-three word description of the error. If we want a rule it has to be simple and enforced everywhere. We can add `<package>` before `<className>`.

Another idea is to make error names follow the same naming style as, how you call them, package paths? I.e. if error is thrown by `engine.model.Element#getChildIndex()` maybe the error name should be same as path but without package name? So it will be something like:

`model.Element#getChildIndex-error-description` or `model-element-getChildIndex-error-description`. That would be an easy and clear rule without place for doubts.

Right now it is `element-getChildIndex-error-description`.

**Comment by Reinmar** [comment]
> We can add `<package>` before `<className>`.

You mean the namespace, right? But it doesn't always matter. E.g. in `ckeditor5-core` there's (will be, in fact) `command/attributecommand.js`. In such case adding `command` to the name makes no sense. That's why I said that I wouldn't try to create any strict rules. This could be sufficient:

* In most cases use `<className>-<methodName>-<errorCode>`.
* You can use the namespace fragment as a denominator in case of multiple classes having the same name within on package, e.g. in the engine: `<namespaceFragment>-<className>-<methodName>-<errorCode>`.
* Some error codes can be shared between multiple methods or even classes and then need to use module name and namespace to create a properly specific name.

Is it enough?

**Comment by scofalik** [comment]
Yes, I've meant `<namespace>`.

Anyway what you described is exactly what I wanted avoid. You propose different error naming concepts in different cases. You say "don't create rule" then you propose how to name them (rule 1) and how to name them in special case (rule 2). Versus my one strict rule which is same everywhere.

**Comment by pjasiun** [comment]
> Some error codes can be shared between multiple methods or even classes and then need to use module name and namespace to create a properly specific name.

I think this is the strongest argument why we can not have a strict conversion. Error name is about the error, should describe the error, it is not about the method or class the error occured in, this is an additional information.

**Comment by scofalik** [comment]
> Some error codes can be shared
I don't know if you understood @Reinmar (or I might have understood him incorrectly).

Why/how/what error can be shared? Right now there are no such examples and given that most complex part is already over I don't think this will happen.

**Comment by Reinmar** [comment]
Is `command-attributeCommand-method-bar: Bar` reasonable? Or `model-operation-operation-method-bar: Bar`? In both cases, you could easily skip one or two pieces of the namespace. 

BTW, we would also need to consider adding package name to the path, because in some situations it may be necessary.

If we'll create a strict rule we're going to end up with some unnecessary long error codes. If you're fine with that, then I'm too. But error codes were meant to be short (because of the code size) and simple (so you're not afraid of throwing when needed).

**Comment by Reinmar** [comment]
> I think this is the strongest argument why we can not have a strict conversion. Error name is about the error, should describe the error, it is not about the method or class the error occured in, this is an additional information.

This is a very good point, in fact. You need flexibility.

**Comment by scofalik** [comment]
Okay, so we settle with adding namespace name when error code is duplicated?

**Comment by Reinmar** [comment]
> Why/how/what error can be shared? Right now there are no such examples and given that most complex part is already over I don't think this will happen.

https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/schema.js#L443 and 
https://github.com/ckeditor/ckeditor5-engine/blob/master/src/model/schema.js#L482

Your own code :D.

> Okay, so we settle with adding namespace name when an error code is duplicated?

Not only when there's a duplicate (BTW, someday we may have a linting check for that), but also when you find that e.g. view and model in the engine contain very similar classes. In such case, we can decide to make error codes more specific.

**Comment by scofalik** [comment]
> Your own code :D.
:)

Okay then.

So, in this issue, we should prefix errors names in model and view in classes that exist in both namespaces. Right?

**Comment by Reinmar** [comment]
Yes, that'd be the minimum. The optimum would be to prefix all (except operations and batches which shouldn't ever repeat).

**Comment by maxbarnas** [comment]
> (except operations and batches which shouldn't ever repeat).

This means `/model/operation/*` and `/model/delta/*` should be untouched?

**Comment by maxbarnas** [comment]
Also, after reading this issue I am still unsure about the proper way of solving this. Take a look at current state of my fixes: https://github.com/ckeditor/ckeditor5-engine/commit/c6f5927a10457638b079cc342c7a776d1f0af280.
