### ISSUE TITLE
Parsing boolean attribute values in view

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#556]
FolowUp: https://github.com/ckeditor/ckeditor5-engine/issues/306

After changing dataprocessor in view from `HTML` to `XML` is not possible to set attribute with boolean value `attribute=true`. It must be `attribute="true"` and value is always a string.

**Comment by pjasiun** [comment]
I think that the fact that it must be `attribute="true"` is not a problem. The problem is that you can not set any type other then string. For setting model values not only strings and booleans, but also numbers and object should works. So it should be possible to set:

```
attribute="5"
attribute='{ "foo": 1, "bar": 2 }'
```

We could `JSON.parse` the value and in case of exception thread it as a string.
