### ISSUE TITLE
FocusObserver should use capturing phase for its events

### ISSUE THREAD

**Issue by szymonkups** [ckeditor/ckeditor5-engine#768]
To get focus events from nested editables `FocusObserver` should add its listener on the `capturing` phase. 

We should allow somehow to pass information about phase to the `observe()` method of `DomEventObserver`. 

Ideas how it could be implemented:
* add `useCapturing` property that will set capturing phase for all events of that observer,
* add `setCapturing( eventName, useCapture )` method to `DomEventObserver` that will allow to set a phase to each event separately,
* change `domEventType` to allow use objects, so we can configure observer's events like this:
```
this.domEventType = [ 'focus', 'blur' ]; 
```
or
```
this.domEventType = [ { 'focus': true }, { 'blur': true } ];
```

**Comment by pjasiun** [comment]
Note that `DomEventObserver` is a very simple class. I'm not sure you need to extend it if it does not fit your needs.

**Comment by szymonkups** [comment]
I feel like setting the phase for events handled by `DomEventObserver` might be useful for other, future observers. To have this functionality only in `FocusObserver` i can just override `observe()` method there or directly use `Observer` class without even using `DomEventObserver`.

**Comment by Reinmar** [comment]
I think that if we have to implement capturing in FocusObserver, then it will be nearly the same cost if we add it to DomEventObserver if we can find a simple API for it. 

I'm against:

```js
this.domEventType = [ { 'focus': true }, { 'blur': true } ];
```

Because it will not be clear what that `true` means.

`useCapturing` property should be enough. It can be boolean now and we can add support for an array of event  names in the future, if we'll need it.
