### ISSUE TITLE
Memory usage and leak tests

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#780]
We've been asked how much memory the data model takes. Later on, we'll also have to tests memory leaks.

**Comment by Reinmar** [comment]
I pushed branch t/780 with a simple manual test. Results are good – loading data 100 times adds 4mb (no garbage collection yet), which means that each document takes 4/100mb (40kb). Pretty nice.

**Comment by scofalik** [comment]
I did some tests too. I've opened article preset manual test: http://localhost:8125/ckeditor5-presets/tests/manual/article.html and made some heap snapshots between monkey clicking the sample.

![image](https://cloud.githubusercontent.com/assets/1502228/24611969/25a3ff3e-1884-11e7-9938-5a24aeef168b.png)

First snapshot is done just after the data is loaded (10MB).

Then I performed 90sec monkey clicking, most of which was typing and removing but also creating new paragraphs, list items, adding and removing attributes, merging, renaming, undo, redo... Anyway that was 90secs of very intensive testing. Second snapshot is done after that (+4MB).

To check whether the memory usage growth is linear and equal to 4MB / 90sec, I once again did similar monkey testing, this for 180secs.

To my surprise, the growth was only by 3MB (instead of expected 8MB). So, I again did 90 secs tests and got a growth of 1.5MB. So it seems that after some kind of "stabilisation", it settled around 1.5MB for 90 secs, which should be around 15MB for 15 mins of intensive work (which should translate to ~20-30 min of normal work).

The last test was "select all + cut + paste", repeated twenty times. The sample content at that time was four times bigger than original sample (compared HTML length of editor). As you can see this resulted in 3.5MB usage.

Of course, I also tried to analyse those snapshots, as much as I was able to.

The first interesting thing to check was what caused +4MB usage on second snapshot (instead of +1.5MB experienced later). 
![image](https://cloud.githubusercontent.com/assets/1502228/24612975/25989006-1887-11e7-8dee-d9e5efaf6d6e.png)

This isn't easy to analyse because most of data is allocated by `(array)`, which obviously makes sense as most of editor data is in various kinds of arrays, containing stuff like: operations (in deltas), nodes (in `NodeList`), etc. Also scrollbar is kinda buggy, overlapping data.

Anyway, second entry is interesting, as `(compiled code)` takes 1MB more than on previous snapshot. I am not exactly sure what `(compiled code)` is (will read more on it) but it is taking less on next snapshots (+200KB, +40KB, +100KB).

Other than that we should be interested in summary for the last monkey-clicking snapshot (Snapshot 5), which shows data after 6 minutes of monkey clicking.

Sorted by "Retained size" - that is size of all elements reachable through that element. I hope that I understood it correctly, but, basically, the higher "retained size" is, the "heavier" references are kept in instances of given class. So, for example if all `RootElement`s would "disappear" (there are two :P), 0.5MB would be freed.

![image](https://cloud.githubusercontent.com/assets/1502228/24613714/6c586e6a-1889-11e7-88af-b1e3e44a5e02.png)

Of course, basic data containers takes most data, but we should focus on our classes. Of course we need to consider that we have big arrays containing a lot of data, but I think we should be able to smaller those by optimising memory usage by instances of our classes.

Funny enough, `LiveSelection` is first, retaining 1.7MB of data! 99% of it is taken by `Symbol(_listeningTo)` which stores A LOT of callbacks :D (1036 to be precise). This means that something in destroying selection live ranges do not work.

Then we have stuff that we would have expected: `WeakInsertDelta` and `NodeList`.  Also a lot of memory is taken by `LiveRange`, and there are a lot of `LiveRange` instances there. This is probably due to the leak in `LiveSelection` - those instances are not removed.

Anyway, after 6 mins of monkey clicking we have 8MB gain. It's hard to calculate exact number of "lost" memory but looking at the "Retained size" column, I'd estimate that with very good garbage collector we might save like ~4MB, and the rest would be: `(compiled code)`, leaks in other places and memory that is actually needed.

I also analysed Snapshot 8 (after cut+paste) and what can be observed there is that most of used memory is taken by `Text` and `NodeList`, that are held in `InsertOperation`s/`InsertDelta`s (big gains for those classes). Other than that same conclusions apply.

![image](https://cloud.githubusercontent.com/assets/1502228/24615519/cca513f4-188e-11e7-990c-ecd850427192.png)

**Comment by Reinmar** [comment]
> Anyway, second entry is interesting, as (compiled code) takes 1MB more than on previous snapshot. I am not exactly sure what (compiled code) is (will read more on it) but it is taking less on next snapshots (+200KB, +40KB, +100KB).

AFAIR it's JIT compiler's memory.

**Comment by Reinmar** [comment]
> Funny enough, LiveSelection is first, retaining 1.7MB of data! 99% of it is taken by Symbol(_listeningTo) which stores A LOT of callbacks :D (1036 to be precise). This means that something in destroying selection live ranges do not work.

!!! This is a great finding. 🎉

**Comment by Reinmar** [comment]
Sorry @scofalik for ruining your fun of debugging this, but this is the callback which is retained:

```
this.listenTo( liveRange, 'change', ( evt, oldRange ) => {
			if ( liveRange.root == this._document.graveyard ) {
				this._fixGraveyardSelection( liveRange, oldRange );
			}

			this.fire( 'change:range', { directChange: false } );
		} );
```

Either it needs to be removed on `_popRange()` or the range itself should be used ass a subject – so not `this.listenTo()`, but `liveRange.listenTo()` (so I guess `liveRange.on()`).

**Comment by Reinmar** [comment]
BTW, as for retainers – I'm not sure if this is not the opposite. Because if you click the item in that panel you get the list of retainers – so variables which are references to that item. And in case of the live selection, if it's listening to too many objects those objects keep refs to it aswell AFAICS .But it's worth checking because I'm not sure here.

**Comment by Reinmar** [comment]
We've done some other tests on different occasions (mainly, performance tests) and memory (despite lack of garbage collection) was never an issue. So, I'm closing this topic.
