### ISSUE TITLE
View tree nodes refactor

### ISSUE THREAD

**Issue by scofalik** [ckeditor/ckeditor5-engine#801]
At the moment, the view nodes structure bases on two classes:
* `Node` - which is the mosty simple one,
* `Element` - which already has all features of `DOMElement` (that is having children, attributes, styles, classes, etc.).

These are made like this to resemble DOM.

Then we have other classes, that are extending above. What's funny (or sad), some of those classes (`EmptyElement`, `UIElement`) actually cripple `Element` functionality. Both of them are elements which should not have children. To achieve this, their constructor throw when children are passed, also `insertChildren` and `appendChildren` always throw. Still, we would like to be able to set attributes or styles on them.

My idea is to switch this structure a bit. Introduce abstract, intermediate level class, that will be able to have attributes, children, styles, but won't be able to have children. Then add a class that will have all the features, like `DOMElement` (and our current `Element`).

![image](https://cloud.githubusercontent.com/assets/1502228/22646712/04aaecc6-ec6e-11e6-9599-eb75736a5ecd.png)

**Comment by Reinmar** [comment]
A solution to a broken OOP design cannot be even more inheritance. I've been warning about this for a long time and @szymonkups experienced issues caused by this design.

We definitely need a call about this. I'm not saying that this proposal is broken, but we must be careful because the first thought regarding OOP is often wrong.

**Comment by pjasiun** [comment]
Yep, I agree with @Reinmar. The whole concept is nice, but we should limit, not increase, the number of levels of inheritance. 6 levels smell bad (5 levels, what we have now, does not smell either).

**Comment by Reinmar** [comment]
OK, turns out this is not something we're planning to work immediately, so we don't need that call now ;>

But in case I forget – the alternative is to keep the inheritance tree as shallow as possible. Inheritance leads to fixing some class features forever. As you mentioned yourself, it's a pity that children of the `Element` class need to be crippled. That's because we didn't expect to have such classes like `EmptyElement`. In fact, when I was commenting on that the last time, warning that we can't use so much inheritance there, we couldn't think of any other base element class... and now we're introducing the `UIElement` which is a new base class.

This proves that the design is constantly changing and you can never be sure what you'll need to add to the picture in a week or year. Hence, favor composition, which gives you much more flexibility.

Without going into the details – we can define interfaces of elements with children (`ParentElementInterface`) and possibly of other types and bring this functionality as a mixin. This means, that if we'll ever need to have `UIElement` with children (or any other unexpected change), we'll be able to do that quite easily.
