### ISSUE TITLE
DocumentFragment#getAncestors( { includeNode: true } ) returns empty array

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#803]
`DocumentFragment#getAncestors` always returns empty array:
```
	getAncestors() {
		return [];
	}
```
but should return array with itself when `includeNode: true` option is set.

It causes: https://github.com/ckeditor/ckeditor5-engine/issues/802

**Comment by Reinmar** [comment]
Model or view?

**Comment by Reinmar** [comment]
Sorry, I can see by the label that it's the view.

**Comment by Reinmar** [comment]
TBH, I don't think that the DF should have getAncestors() at all. It makes no sense for as the DF has no ancestors.

**Comment by scofalik** [comment]
The origin of this method in view is probably to make view as similar to model as possible (the big refactor of engine I did some time ago).

In model this was needed to have same interface for `Element` and `DocumentFragment` as both of those may be used as parameters in some algorithms.

**Comment by oskarwrobel** [comment]
Docs: "Added for compatibility reasons."

**Comment by oskarwrobel** [comment]
If we want to keep this method I think we should fix this issue.

**Comment by Reinmar** [comment]
> The origin of this method in view is probably to make view as similar to model as possible (the big refactor of engine I did some time ago).
> 
> In model this was needed to have same interface for Element and DocumentFragment as both of those may be used as parameters in some algorithms.

Wait... but there's no such method in the model's DocFrag. Only `Node` has this method.

**Comment by oskarwrobel** [comment]
I've checked what happens when `getAncestors` is removed from `view.DocumentFragment`.
This is the only failing test in the entire CKE5:
```
      ✖ should return empty array
        Chrome 55.0.2883 (Mac OS X 10.12.2)
      TypeError: fragment.getAncestors is not a function
          at Context.it (packages/ckeditor5-engine/tests/view/documentfragment.js:2015:21)
```

**Comment by Reinmar** [comment]
Thanks :) So I guess we can safely remove it. No one should be trying to call `getAncestors()` on a doc frag.

**Comment by scofalik** [comment]
Okay, so it's probably there because there is a `getPath` in `ModelDocumentFragment` and `getAncestors` was treated as "view's `getPath` equivalent". You may remove it 🤷‍♂️ but it was added there for the unifying reasons in the first place. It's better to have same API on similar objects rather than make people WTF (why it's not there) or, even worse, check object's class to apply different algorithm (because `getAncestors` will be missing).

**Comment by oskarwrobel** [comment]
> It's better to have same API on similar objects rather than make people WTF (why it's not there) or, even worse, check object's class to apply different algorithm (because getAncestors will be missing).

I agree with you. `Position` class is a good example where we will need check if object is a DocFrag.
Here https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/position.js#L145-L147 or here https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/position.js#L205-L206.

**Comment by scofalik** [comment]
Yes, please fix this as it resolves other issue.

**Comment by Reinmar** [comment]
> It's better to have same API on similar objects rather than make people WTF (why it's not there) or, even worse, check object's class to apply different algorithm (because getAncestors will be missing).

It was a WTF for me that DF had this method ;) You could tell that in order to unify the APIs text nodes will get `insertChildren()` and elements the `data` property ;P DFs don't ever have ancestors so they should not have such method.

**Comment by scofalik** [comment]
Great, than you have to write special code and provide `if`s to check what instance is given object. I know you are a purist but there is also sanity.

**Comment by Reinmar** [comment]
> Great, then you have to write special code and provide ifs to check what instance is given object. I know you are a purist but there is also sanity.

Exactly like you have a special code checking if something is a text node or element. 

BTW, I looked at the first case brought by @oskarwrobel: https://github.com/ckeditor/ckeditor5-engine/blob/master/src/view/position.js#L145-L147

How can `this.parent` be a docfrag if the documentation says that `this.parent` is a `Node`? :|

**Comment by Reinmar** [comment]
PS. Don't get me wrong. I'm for sanity as well, so I was about to accept Oskar's PR. However, then he wrote that there's just 1 test broken after removing the only `DF.getAncestors()` that we have. So then I changed my mind because the sanity told me that we're messing our code with unneeded methods.

If that's really a recurring theme that DF can end up in places where you normally except nodes, then I'm ok with a stub `getAncestors()`. But so far, all evidences are against that.

**Comment by scofalik** [comment]
The doc is probably outdated.

One place where this can happen was already provided by @oskarwrobel. Of course, we can say "view position cannot be directly in document fragment". What then?
1. This is "incompatible" with model.
2. It has more consequences, for example you cannot walk view document fragment using view tree walker. 

Of course we can check where `getAncestors()` is used and provide if's there if needed. Maybe that will solve issues now, but I am not sure if it won't come up later.

> If that's really a recurring theme that DF can end up in places where you normally except nodes, then I'm ok with a stub

One of places where this can happen are converters. This is a place where you might expect a node or doc frag.

**Comment by Reinmar** [comment]
OK, so to sum up:

1. Please report a ticket for the outdated docs and potentially missing. This is a serious issue if a position can end up in a doc frag and tests for that are incomplete (e.g. if there was a test for `position.getAncestors()`, then... we'd have such method already).
2. Please report a ticket for a general review of where doc frag can end up where it's not expected. All these places should be reviewed for incorrect documentation and missing tests.

Finally, a thing to remember for the future – pretending that X is Y, when it's not may lead to silent errors and lots of wasted time.

DF is not a node, but you want it to be a node for the sake of less code branching. Fine. But the next thing we see is adding `remove()` to the DF, because one may want to use that method (how's it different from `getAncestors()` anyway?). Next day, you waste a couple of hours debugging an algorithm which should fail or is failing in a very strange way because a DF was used in a place of a normal node and some totally reasonable code made totally unreasonable things with it.

I've seen those things far more times than I'd like to. CKE4 was full of such quirks – weird ducktyping or hacking one algorithm by passing unexpected arguments to it (because they seemed to do the job). Believe me, this is only considered an ugly hack later on. We've been fighting for years do get rid of such a code.

So the sanity changes with time and your POV. What may seem a good and simple solution now may shock your children... or even you, before you check the `git blame` ;).

**Comment by Reinmar** [comment]
Continuing my complaining – I'd like to point one more important detail. Relying on ducktyping and interface matching is a super handy feature of weakly typed languages. However, it comes at a cost – you lose certainty and static validation. The advantage of strong typing is your safety, but it comes at a cost too – more bloat.

So how to choose which option to take? (Note: of course, JS is weakly typed, but proper documentation + explicit type protects you. You can also go with additions like TS, but not in our case, unfortunately) For me, the rule of thumb is – the lower in the architecture, the safer your should be. Because the lower you are, the more code depends on you and the bigger impact of bugs and decisions in general. 

So, in the engine we should be explicit and precise. In an end-feature implementation, we can go for a shorter, more dynamic path.

You already listed a couple of places which might be affected by this decision and might've incorrectly worked so far due to an inexplicit use of DF. Of course, we can polish those places, but we can be sure that this is just the tip of the iceberg.

This case even reminds me an issue I encountered some time ago – https://github.com/ckeditor/ckeditor5-engine/issues/742. I found the case with the array only by an accident. The documentation wasn't clear about it and the number of options was left too wide.

**Comment by scofalik** [comment]
Reported #805 and #806.

#805 will be done now to resolve issues. #806 is reported for later.

**Comment by scofalik** [comment]
Also reported #807.
