### ISSUE TITLE
Unwrapping isn't correctly converted to the view

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#823]
Weird things are happening:

![feb-19-2017 15-02-36](https://cloud.githubusercontent.com/assets/156149/23103941/2ddf930c-f6c4-11e6-8f28-9132bfd1526d.gif)

**Comment by Reinmar** [comment]
The model is changed correctly, but the change isn't converted to the view.

**Comment by Reinmar** [comment]
Also, sometimes I get this error when trying to remove quote which I just applied:

![image](https://cloud.githubusercontent.com/assets/156149/23104019/ed3edf0e-f6c5-11e6-9d8a-58f1c009b922.png)

**Comment by Reinmar** [comment]
The first remove operation is totally wrong – it should cover the entire `<p>`.

![image](https://cloud.githubusercontent.com/assets/156149/23104379/0dd9919e-f6cd-11e6-8813-95040a2395e1.png)

**Comment by Reinmar** [comment]
I checked that `move()` from M2V converters works on such a model range (ofc it's mapped incorrectly at that point because the model structure is already changes):

```html
<paragraph>abc</paragraph><paragraph>[x]x</paragraph><messageQuote></messageQuote><paragraph>def</paragraph>
```

which converts to this view range:

```html
<div><p>abc</p><blockquote><p>{x}x</p></blockquote><p>def</p></div>
```

The model range is 1,0-1,1 which previously pointed to the content of `<messageQuote>` (so the range is ofc correct). But since the paragraph was inserted in the model before the `<messageQuote>` the range should be transformed.

Should this be done like in `remove()`?

```js
const modelRange = ModelRange.createFromPositionAndShift( data.sourcePosition, data.item.offsetSize );
```

**Comment by Reinmar** [comment]
I see that some converter functions transform the position themselves like this:

```js
const sourcePos = data.sourcePosition._getTransformedByInsertion( data.targetPosition, data.item.offsetSize );
```

I'm surprised though how few of them.

**Comment by Reinmar** [comment]
OK, it seems that I managed to fix the issue. I pushed t/823 with a prototype.

**Comment by Reinmar** [comment]
But the error mentioned in https://github.com/ckeditor/ckeditor5-engine/issues/823#issuecomment-280928755 is still reproducible when trying to remove the quote from two blocks :>

Another round of debugging tomorrow.

**Comment by scofalik** [comment]
> I see that some converter functions transform the position themselves like this

This is actually an exception from the rule. Markers converters are "special" and we even discussed moving them out of this file and putting them in `ModelConversionDispatcher`, because those converters, in fact, do not convert anything. All they do is using `ModelConversionDispatcher` functions, so _dispatching events_.

The rule (at least for now :P) is that you should already have correct data in the converter and just operate on it -- convert a change from model (input data) to changes on view (output action). Converters should have correct data. Corrections should be done in `ModelConversionDispatcher`: https://github.com/ckeditor/ckeditor5-engine/blob/master/src/conversion/modelconversiondispatcher.js#L214-L235

I'd start from looking for bugs in the part of code linked above.

**Comment by Reinmar** [comment]
OK, I had a feeling that this may not be the right place. In fact, I understand now why – you shouldn't need to think about this when implementing your own converters.

**Comment by Reinmar** [comment]
It's the same issue as in https://github.com/ckeditor/ckeditor5-engine/issues/847.
