### ISSUE TITLE
Parent instead of children as a third parameter of Element contructor

### ISSUE THREAD

**Issue by pjasiun** [ckeditor/ckeditor5-engine#867]
I just realized that it would be nice to have `parent` instead of `children` as the third parameter of the element constructor.

Usually, in the code, first you create parent, then children, it seems to be more natural, so you need to call additional `appendChild`:

```js
const imageElement = new Element( 'image', { src: 'foo.png' } );
const captionElement = new Element( 'caption', null, 'foo bar' );
const imageElement.appendChild( captionElement );
rootElement.appendChild( imageElement );
```

Or change the order:

```js
const captionElement = new Element( 'caption', null, 'foo bar' );
const imageElement = new Element( 'image', { src: 'foo.png' }, imageElement );
rootElement.appendChild( imageElement );
```

Note that text is an exception here.

But still I found this order more natural:

```js
const imageElement = new Element( 'image', { src: 'foo.png' }, rootElement );
const captionElement = new Element( 'caption', null, imageElement );
captionElement.appendChildren( 'foo bar' );
```

It's also compatible with changes proposed here: https://github.com/ckeditor/ckeditor5-engine/issues/858#issuecomment-284701045.

**Comment by Reinmar** [comment]
> But still I found this order more natural:

For me it's exactly the opposite. You want a child element to add itself to the parent? I've never seen API like this. I would have no idea what it is. Not without a reason, you designed the API to accept children in the first place and have it used in bazillion of places.

So, as I commented in #866, let's find out an easy way to create trees of model and view elements. Both of your proposals are not a solution.

E.g. (from the top of my head):

```js
document
    .createElement( 'image', { src: 'foo' } )
        .appendElement( 'caption', { src: 'foo' } )
            .appendText( 'caption text' ).up()
        .appendElement( 'sthElse );
```

We could also make this API similar to the templates from the UI view. Or work on both APIs at the same time, because the one from the UI lib is not perfect as well.

**Comment by pjasiun** [comment]
Fixed by https://github.com/ckeditor/ckeditor5-engine/issues/858.
