### ISSUE TITLE
LivePosition is still broken after move

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-engine#877]
Initial live range:

```html
<messageQuote><paragraph>abc</paragraph><paragraph>x[x</paragraph></messageQuote><paragraph>d]ef</paragraph>
```

The move (`<p>` out of `<messageQuote>`):

```html
<messageQuote><paragraph>abc</paragraph>[<paragraph>xx</paragraph>]</messageQuote>[]<paragraph>def</paragraph>
```

**Comment by Reinmar** [comment]
The actual position I get:

```html
<messageQuote><paragraph>abc</paragraph>[</messageQuote><paragraph>xx</paragraph><paragraph>de]f</paragraph>
```

**Comment by Reinmar** [comment]
And I get the same error with a mirrored case – when selection's left end is outside of `<mq>` and I'm moving first paragraph from `<mq>` before that `<mq>`.

**Comment by Reinmar** [comment]
OK, merge doesn't work too (`^` is a merge position):

```html
<messageQuote><heading>a[bc</heading></messageQuote>^<messageQuote><paragraph>x]x</paragraph><paragraph>yy</paragraph></messageQuote><paragraph>def</paragraph>
```

Actual result:

```html
<messageQuote><heading>a[bc</heading><paragraph>xx</paragraph><paragraph>yy</paragraph></messageQuote>]<paragraph>def</paragraph>
```

**Comment by scofalik** [comment]
The problem, kinda, lies in `Range#_getTransformedByDocumentChange`. This is the method that is used to transform `LiveRange` (and for `Marker`s OT).

The problem is that, with move change, we cannot have a perfect range transformation because we don't know what is the model state. Since `LiveRange` transformations have to be exactly same as `Marker`s transformation, we cannot check model state (it is unavailable during OT). Additionally, `Undo` will probably use this method in future too (`Undo` is much like OT).

This means that we have to create transformed range only basing on range and change data. We already have `Range#_getTransformedByMove` but it is very "exact", which not always goes in pair with UX.

Here are what we would like to achieve:
`<p>x[x</p><w><p>y]y</p></w>`
When `<p>yy</p>` is moved:
`<p>x[x</p><w></w><p>y]y</p>`

The problem is that we don't know if `<p>yy</p>` was the only element in `<w>`:
`<p>x[x</p><w><p>y]y</p><p>zz</p></w>` -> `<p>x[x</p><w><p>zz</p></w><p>y]y</p>`.

Suddenly, we included `<p>zz</p>` in a range, in which it wasn't before.

We could do hacks like this for `Merge`, `Split`, `Wrap` and `UnwrapDelta` because we knew what exactly is happening (for example we know that when unwrapping, we move all the content from `<w>`). But we do not have this certainty in case of `MoveDelta`.

Anyway, we decided that we are fine with including extra nodes. We are leaving this change in `_getTransformedByDocumentChange`, so OT will work as it did (`_getTransformedByMove` is not changed). However `Marker`s and `LiveRange`s will be transformed with those new rules in mind.

**Comment by Reinmar** [comment]
> Anyway, we decided that we are fine with including extra nodes.

I think that the critical argument supporting that was that we can't think of move operations moving nodes further than to a touching position. We're mostly using move to e.g. move elements out of some element. Like:

```html
<p>xxx</p>
<messageQuote>
  <p>y[]yy</p>
  <p>zzz</p>
  ...
```

If we want to remove quote from "yyy" we move that paragraph before the `<mQ>` element.

In all such cases extending the range will be fine.

**Comment by scofalik** [comment]
As a note, my biggest concern drag and drop.

When you drag and drop part of tree that contains range boundary of marker, the marker will get expanded, which I don't like at all. Similarly, during collaborative editing one client might move other client's selection boundary, expanding their selection, which is really bad.

However @Reinmar pointed out to me that drag and drop will most probably be executed as remove + processing + insert.
