### ISSUE TITLE
selectionChange is not fired on input and delete

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-engine#909]
See:
![apr-05-2017 23-10-05](https://cloud.githubusercontent.com/assets/1057056/24727136/30a7b6c8-1a55-11e7-8961-ebcdc01094e4.gif)

**Comment by pjasiun** [comment]
According to the docs (https://github.com/ckeditor/ckeditor5-engine/blob/166ec4d1d3ba93b727212cf5fb932db0cda49cbd/src/view/observer/selectionobserver.js#L194-L195):

> Fired when the selection has changed. This event is fired only when the selection change was the only change that happened in the document, and old selection is different than the new selection.

And it can not be done a different way. Selection change event is fired when the DOM event occurred. View document is changed as a result of the model change. It means that when selection change is fired there is no change in the view yet. If both content and selection change it may happen that the element which should be the parent of the selection is not yet in the view.

The more proper event to use here is `view.selection.on( 'change', ... );` which is fired as a result of the model and view change.

At the same time, I realized how tricky it is. We should do something to hide observers event since the fact that they are fired on the view document is misleading.
